name: Go
on: [push, pull_request]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  gitversion:
    name: GitVersion
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Cache GitVersion tool
      - name: Cache GitVersion
        uses: actions/cache@v4
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-gitversion-6.x
          restore-keys: |
            ${{ runner.os }}-gitversion-

      - name: Install GitVersion
        id: install-gitversion
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: '6.x'
          preferLatestVersion: true
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.1.0
    outputs:
      major: ${{ steps.gitversion.outputs.major }}
      minor: ${{ steps.gitversion.outputs.minor }}
      majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
      semVer: ${{ steps.gitversion.outputs.semVer }}
      version: ${{ github.ref_name == github.event.repository.default_branch && steps.gitversion.outputs.majorMinorPatch || steps.gitversion.outputs.semVer }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ gitversion ]
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.25"
          - "tip"
    env:
      GOPATH: ${{ github.workspace }}/go
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
        with:
          path: ${{ github.workspace }}/go/src/gopkg.in/yaml.${{ needs.gitversion.outputs.version }}

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ${{ github.workspace }}/go/pkg
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-
            ${{ runner.os }}-go-

      - name: Set up Go ${{ matrix.go }}
        if: matrix.go != 'tip'
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: false  # We're using our own cache above
      # Cache Go tip build
      - name: Get Go tip commit
        if: matrix.go == 'tip'
        id: gotip-version
        run: |
          GOTIP_COMMIT=$(curl -s 'https://go.googlesource.com/go/+/refs/heads/master?format=JSON' | awk '/"commit"/{print substr($2,2,40);exit}')
          echo "commit=${GOTIP_COMMIT}" >> $GITHUB_OUTPUT
          echo "short=${GOTIP_COMMIT:0:7}" >> $GITHUB_OUTPUT

      - name: Cache Go tip
        if: matrix.go == 'tip'
        uses: actions/cache@v4
        with:
          path: ~/gotip
          key: ${{ runner.os }}-gotip-${{ steps.gotip-version.outputs.commit }}
          restore-keys: |
            ${{ runner.os }}-gotip-

      - name: Set up Go ${{ matrix.go }}
        if: matrix.go == 'tip'
        run: |
          export GOROOT_BOOTSTRAP=`go env GOROOT`
          export GOROOT=$HOME/gotip

          # Check if gotip is already cached
          if [ ! -f "$GOROOT/VERSION" ] || [ "$(cat $GOROOT/VERSION 2>/dev/null)" != "gotip-${{ steps.gotip-version.outputs.short }}" ]; then
            echo "Building Go tip..."
            rm -rf $GOROOT
            mkdir -p $GOROOT
            cd $GOROOT

            echo "${{ steps.gotip-version.outputs.commit }}" >HEAD
            echo "gotip-${{ steps.gotip-version.outputs.short }}" >VERSION

            curl -s -o go.tar.gz https://go.googlesource.com/go/+archive/`cat HEAD`.tar.gz
            tar xfz go.tar.gz

            cd src
            bash make.bash
          else
            echo "Using cached Go tip build"
          fi

          echo "GOROOT=$GOROOT" >> $GITHUB_ENV
          echo "$GOROOT/bin" >> $GITHUB_PATH
      - run: go version
      - run: go get -t ./...
        working-directory: ${{ github.workspace }}/go/src/gopkg.in/yaml.${{ needs.gitversion.outputs.version }}
      - run: go test .
        working-directory: ${{ github.workspace }}/go/src/gopkg.in/yaml.${{ needs.gitversion.outputs.version }}

  release:
    name: Release
    if: ${{ success() && github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    needs: [ gitversion, test ]
    steps:
      - name: GitHub Actions Bot Configuration
        id: bot_config
        env:
          GITHUB_BOT_EMAIL: elio@elio.eti.br
          GITHUB_BOT_USERNAME: Elio Severo Junior
        shell: bash -l {0}
        run: |
          #!/usr/bin/env bash
          
          set -euo pipefail
          
          echo "GITHUB_BOT_EMAIL=${{ env.GITHUB_BOT_EMAIL }}" >> $GITHUB_ENV
          echo "GITHUB_BOT_USERNAME=${{ env.GITHUB_BOT_USERNAME }}" >> $GITHUB_ENV
          
          git config --global author.email "${{ env.GITHUB_BOT_EMAIL }}"
          git config --global author.name "${{ env.GITHUB_BOT_USERNAME }}"
          git config --global committer.email "${{ env.GITHUB_BOT_EMAIL }}"
          git config --global committer.name "${{ env.GITHUB_BOT_USERNAME }}"
          git config --global init.defaultBranch ${{ github.event.repository.default_branch }}
          git config --global pull.ff only
          git config --global pull.rebase true
          git config --global push.autosetupremote true
          git config --global push.followTags true
          git config --global user.email "${{ env.GITHUB_BOT_EMAIL }}"
          git config --global user.name "${{ env.GITHUB_BOT_USERNAME }}"
          
          if [[ "${{ github.event.act }}" == "true" ]];
          then
          echo "Disabling GPG Configurations..."
          git config --local --unset commit.gpgsign 2>/dev/null
          git config --local --unset gpg.program 2>/dev/null
          git config --local --unset user.signingkey 2>/dev/null
          else
          echo "Initializing Git Repository..."
          git init ${{ github.workspace }}
          fi
          
          echo "bot_email=${{ env.GITHUB_BOT_EMAIL }}" >> $GITHUB_OUTPUT
          echo "bot_user=${{ env.GITHUB_BOT_USERNAME }}" >> $GITHUB_OUTPUT

      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Tag
        id: tag
        shell: bash -l {0}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          #!/usr/bin/env bash
          
          function tagger() {
            VERSION=$1
            echo "Releasing Version: ${VERSION}"
            TAG_EXISTS=$(git ls-remote -q --tags | grep -q "refs/tags/${VERSION}$" && echo true || echo false)
            if [[ "${TAG_EXISTS}" = true ]];
            then
              HAS_RELEASE=$(gh release list --json tagName -q '.[].tagName' | grep -E "^(${VERSION})$" && echo true || echo false)
              if [[ "${HAS_RELEASE}" == true ]];
              then
                gh release delete --yes ${VERSION}
              fi
              git push origin --delete ${VERSION}
              git tag -d ${VERSION}
            fi
          
            echo
            git tag -a ${VERSION} -m "chore: Release Version ${VERSION}"
            git push -f --tags --follow-tags
            git push --set-upstream origin ${{ github.ref_name }}
            echo
            echo
          }
          
          tagger "v${{ needs.gitversion.outputs.version }}"
          if [[ "${{ github.ref_name  }}" == "${{ github.event.repository.default_branch }}" ]];
          then
            tagger "v${{ needs.gitversion.outputs.major }}.${{ needs.gitversion.outputs.minor }}"
            tagger "v${{ needs.gitversion.outputs.major }}"
          fi

      - name: Release
        id: release
        shell: bash -l {0}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          #!/usr/bin/env bash
          
          if [[ "${{ github.ref_name  }}" == "${{ github.event.repository.default_branch }}" ]];
          then
            gh release list | grep Draft | awk '{print $1 " \t"}' | while read -r draft; do echo "Removing Draft Releases: ${draft}"; gh release delete --yes "${draft}"; done
            gh release create v${{ needs.gitversion.outputs.version }} --generate-notes --verify-tag --latest
          fi